GRANT ALL ON SCHEMA public TO uniyoklama;
GRANT CREATE ON SCHEMA public TO uniyoklama;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO uniyoklama;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO uniyoklama;
